"""add release_year and director to movies

Revision ID: 2f07ef838c55
Revises: 6bcd50c8ca87
Create Date: 2026-01-20 18:57:33.911413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f07ef838c55'
down_revision: Union[str, Sequence[str], None] = '6bcd50c8ca87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_reviews', 'review_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('movie_reviews', 'review_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_reviews', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('movies', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('director', sa.String(length=200), nullable=True))
    op.alter_column('photos', 'cinema_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('photos', 'photo_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('photos', 'insert_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('photos', 'updated_at')
    op.drop_column('photos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('photos', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('photos', 'insert_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('photos', 'photo_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('photos', 'cinema_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('movies', 'director')
    op.drop_column('movies', 'release_year')
    op.alter_column('movie_reviews', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movie_reviews', 'review_rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_reviews', 'review_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
