"""add tickets

Revision ID: 7d9b54781d78
Revises: 81b0464a4514
Create Date: 2026-01-14 23:18:33.963407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9b54781d78'
down_revision: Union[str, Sequence[str], None] = '81b0464a4514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('movie_time_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_3d', sa.Boolean(), nullable=False),
    sa.Column('is_vip_ticket', sa.Boolean(), nullable=False),
    sa.Column('is_couple_ticket', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['movie_time_id'], ['movie_times.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['rows.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_time_id', 'seat_id', name='uq_ticket_movietime_seat'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
