"""add rows and seats

Revision ID: 81b0464a4514
Revises: 7033e03ebcbe
Create Date: 2026-01-14 22:41:23.298440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b0464a4514'
down_revision: Union[str, Sequence[str], None] = '7033e03ebcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('row_name', sa.String(length=50), nullable=False),
    sa.Column('number_of_seats', sa.Integer(), nullable=False),
    sa.Column('is_vip_row', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hall_id', 'row_name', name='uq_rows_hall_rowname')
    )
    op.create_index(op.f('ix_rows_id'), 'rows', ['id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('seat_name', sa.String(length=50), nullable=False),
    sa.Column('is_vip_seat', sa.Boolean(), nullable=False),
    sa.Column('is_couple_seat', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['rows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'seat_name', name='uq_seats_row_seatname')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_rows_id'), table_name='rows')
    op.drop_table('rows')
    # ### end Alembic commands ###
